checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - tests/*
        - docs/*
        - testproject/*

tools:
    external_code_coverage:
        timeout: 300
        runs: 1
