# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wristband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modificado em ')),
                ('wristband_code', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='Pulseira')),
                ('entry_on', models.DateTimeField(null=True, verbose_name='Entrou em')),
                ('wallet_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Carteira')),
                ('shop_created_on', models.DateTimeField(blank=True, null=True, verbose_name='Comprado em')),
            ],
            options={
                'verbose_name': 'Pulseira',
                'verbose_name_plural': 'Pulseiras',
                'ordering': ('-entry_on', 'shop_created_on'),
            },
        ),
        migrations.CreateModel(
            name='LocalTicket',
            fields=[
                ('wristband_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gate.Wristband')),
            ],
            options={
                'verbose_name': 'Ticket Local',
                'verbose_name_plural': 'Tickets Locais',
                'ordering': ('-entry_on',),
            },
            bases=('gate.wristband',),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('wristband_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gate.Wristband')),
                ('uuid', models.CharField(blank=True, db_index=True, editable=False, max_length=36, null=True, unique=True, verbose_name='QRCode')),
                ('qrcode_requires_identification', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
            bases=('gate.wristband', models.Model),
        ),
        migrations.CreateModel(
            name='GuestTicket',
            fields=[
                ('qrcode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gate.QRCode')),
                ('person_name', models.CharField(blank=True, max_length=100, verbose_name='Nome da Pessoa')),
                ('person_document', models.CharField(blank=True, max_length=14, verbose_name='Documento da Pessoa')),
                ('list_name', models.CharField(max_length=100, verbose_name='Nome da Lista de Convidados')),
            ],
            options={
                'verbose_name': 'Ticket de Convidado',
                'verbose_name_plural': 'Tickets de Convidados',
                'ordering': ('-entry_on', 'list_name'),
            },
            bases=('gate.qrcode', models.Model),
        ),
        migrations.CreateModel(
            name='PaperTicket',
            fields=[
                ('qrcode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gate.QRCode')),
                ('batch_name', models.CharField(max_length=100, verbose_name='Nome do Lote')),
                ('batch_line', models.PositiveIntegerField(verbose_name='Linha do Lote')),
            ],
            options={
                'verbose_name': 'Ticket de Papel',
                'verbose_name_plural': 'Tickets de Papel',
                'ordering': ('-entry_on', 'shop_created_on'),
            },
            bases=('gate.qrcode',),
        ),
        migrations.CreateModel(
            name='WebTicket',
            fields=[
                ('qrcode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gate.QRCode')),
                ('person_name', models.CharField(blank=True, max_length=100, verbose_name='Nome da Pessoa')),
                ('person_document', models.CharField(blank=True, max_length=14, verbose_name='Documento da Pessoa')),
                ('product_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Produto')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='Nome do Comprador')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Email do Comprador')),
            ],
            options={
                'verbose_name': 'Ticket Web',
                'verbose_name_plural': 'Tickets Web',
                'ordering': ('-entry_on', 'shop_created_on'),
            },
            bases=('gate.qrcode', models.Model),
        ),
    ]
