# Generated by Django 2.0.1 on 2018-01-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wristband',
            name='entry_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrou em'),
        ),
    ]
