# Generated by Django 2.0.1 on 2018-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_auto_20180111_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='wristband',
            name='wallet_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wristband',
            name='wristband_code',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'WBAND_CODE_EXISTS: Esta pulseira já foi registrada em nosso sistema.'}, max_length=10, null=True, unique=True, verbose_name='Pulseira'),
        ),
    ]
