# Generated by Django 2.0.1 on 2018-01-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_auto_20180123_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperticket',
            options={'ordering': ('-entry_on', 'shop_purchase_date'), 'verbose_name': 'Ticket de Papel', 'verbose_name_plural': 'Tickets de Papel'},
        ),
        migrations.AlterModelOptions(
            name='webticket',
            options={'ordering': ('-entry_on', 'shop_purchase_date'), 'verbose_name': 'Ticket Web', 'verbose_name_plural': 'Tickets Web'},
        ),
        migrations.AlterModelOptions(
            name='wristband',
            options={'ordering': ('-entry_on', 'shop_purchase_date'), 'verbose_name': 'Pulseira', 'verbose_name_plural': 'Pulseiras'},
        ),
        migrations.RenameField(
            model_name='wristband',
            old_name='shop_created_on',
            new_name='shop_purchase_date',
        ),
    ]
